name: dm2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.12.7=py39h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.3.1=py39h06a4308_0
  - python=3.9.15=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py39h06a4308_0
  - sqlite=3.40.0=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - tzdata=2022g=h04d1e81_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.8=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - addict==2.4.0
      - asttokens==2.2.1
      - attrs==22.2.0
      - backcall==0.2.0
      - charset-normalizer==2.1.1
      - click==8.1.3
      - comm==0.1.2
      - configargparse==1.5.3
      - contourpy==1.0.6
      - cycler==0.11.0
      - dash==2.7.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - debugpy==1.6.4
      - decorator==5.1.1
      - entrypoints==0.4
      - executing==1.2.0
      - fastjsonschema==2.16.2
      - flask==2.2.2
      - fonttools==4.38.0
      - idna==3.4
      - importlib-metadata==6.0.0
      - ipykernel==6.19.4
      - ipython==8.7.0
      - ipywidgets==8.0.4
      - itsdangerous==2.1.2
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - jsonschema==4.17.3
      - jupyter-client==7.4.8
      - jupyter-core==5.1.1
      - jupyterlab-widgets==3.0.5
      - kiwisolver==1.4.4
      - markupsafe==2.1.1
      - matplotlib==3.6.2
      - matplotlib-inline==0.1.6
      - matplotlib-scalebar==0.8.1
      - nbformat==5.5.0
      - nest-asyncio==1.5.6
      - numpy==1.24.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - open3d==0.16.0
      - packaging==22.0
      - pandas==1.5.2
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.4.0
      - platformdirs==2.6.2
      - plotly==5.11.0
      - prompt-toolkit==3.0.36
      - psutil==5.9.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.14.0
      - pyparsing==3.0.9
      - pyquaternion==0.9.9
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2022.7
      - pyyaml==6.0
      - pyzmq==24.0.1
      - requests==2.28.1
      - scikit-learn==1.2.0
      - scipy==1.9.3
      - seaborn==0.12.2
      - six==1.16.0
      - stack-data==0.6.2
      - tenacity==8.1.0
      - threadpoolctl==3.1.0
      - torch==1.13.1
      - torchvision==0.14.1
      - tornado==6.2
      - tqdm==4.64.1
      - traitlets==5.8.0
      - typing-extensions==4.4.0
      - urllib3==1.26.13
      - wcwidth==0.2.5
      - werkzeug==2.2.2
      - widgetsnbextension==4.0.5
      - zipp==3.11.0
prefix: /home/xl3136/miniconda3/envs/dm2
